name: Printshop
favicon: null
layout_spectrum: 0.7893822875339538
typography_spectrum: 0.17824629321694374
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.16151722357608378
  lightness: 0.40018634777516127
  saturation: 0.4793879692442715
  rhythmicContrast: 0.9205522995907813
purpose: []
